/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Object = System.Object;
using InvalidOperationException = System.InvalidOperationException;
using Exception = System.Exception;
using ArgumentNullException = System.ArgumentNullException;
using SystemEventHandler = System.EventHandler;
using Guid = System.Guid;
using DateTimeOffset = System.DateTimeOffset;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using IApiAccessor = Finbourne.Sdk.Client.IApiAccessor;
using Finbourne.Sdk.Extensions;
using Finbourne.Sdk.Client.Auth;
using Finbourne.Sdk.Services.Lusid.Model;

namespace Finbourne.Sdk.Services.Lusid.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDerivedTransactionPortfoliosApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio
        /// </summary>
        /// <remarks>
        /// Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Portfolio</returns>
        Portfolio CreateDerivedPortfolio(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio
        /// </summary>
        /// <remarks>
        /// Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of Portfolio</returns>
        Finbourne.Sdk.Client.ApiResponse<Portfolio> CreateDerivedPortfolioWithHttpInfo(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, ConfigurationOptions? opts = null);
        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details
        /// </summary>
        /// <remarks>
        /// Delete all the portfolio details for a derived transaction portfolio.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        DeletedEntityResponse DeleteDerivedPortfolioDetails(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details
        /// </summary>
        /// <remarks>
        /// Delete all the portfolio details for a derived transaction portfolio.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteDerivedPortfolioDetailsWithHttpInfo(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, ConfigurationOptions? opts = null);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDerivedTransactionPortfoliosApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio
        /// </summary>
        /// <remarks>
        /// Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of Portfolio</returns>
        System.Threading.Tasks.Task<Portfolio> CreateDerivedPortfolioAsync(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio
        /// </summary>
        /// <remarks>
        /// Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (Portfolio)</returns>
        System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<Portfolio>> CreateDerivedPortfolioWithHttpInfoAsync(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details
        /// </summary>
        /// <remarks>
        /// Delete all the portfolio details for a derived transaction portfolio.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        System.Threading.Tasks.Task<DeletedEntityResponse> DeleteDerivedPortfolioDetailsAsync(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details
        /// </summary>
        /// <remarks>
        /// Delete all the portfolio details for a derived transaction portfolio.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteDerivedPortfolioDetailsWithHttpInfoAsync(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDerivedTransactionPortfoliosApi : IDerivedTransactionPortfoliosApiSync, IDerivedTransactionPortfoliosApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DerivedTransactionPortfoliosApi : IDerivedTransactionPortfoliosApi
    {
        private Finbourne.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DerivedTransactionPortfoliosApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DerivedTransactionPortfoliosApi(Finbourne.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = configuration;
            this.Client = new Finbourne.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Finbourne.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Finbourne.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DerivedTransactionPortfoliosApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DerivedTransactionPortfoliosApi(Finbourne.Sdk.Client.ISynchronousClient client, Finbourne.Sdk.Client.IAsynchronousClient asyncClient, Finbourne.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Finbourne.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Finbourne.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Finbourne.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Finbourne.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Finbourne.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Portfolio</returns>
        public Portfolio CreateDerivedPortfolio(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<Portfolio> localVarResponse = CreateDerivedPortfolioWithHttpInfo(scope, createDerivedTransactionPortfolioRequest, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of Portfolio</returns>
        public Finbourne.Sdk.Client.ApiResponse<Portfolio> CreateDerivedPortfolioWithHttpInfo(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling DerivedTransactionPortfoliosApi->CreateDerivedPortfolio");
            }

            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.Data = createDerivedTransactionPortfolioRequest;

            localVarRequestOptions.Operation = "DerivedTransactionPortfoliosApi.CreateDerivedPortfolio";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<Portfolio, AbstractOpenAPISchema>("/api/api/derivedtransactionportfolios/{scope}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDerivedPortfolio", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of Portfolio</returns>
        public async System.Threading.Tasks.Task<Portfolio> CreateDerivedPortfolioAsync(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<Portfolio> localVarResponse = await CreateDerivedPortfolioWithHttpInfoAsync(scope, createDerivedTransactionPortfolioRequest, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CreateDerivedPortfolio: Create derived portfolio Create a derived transaction portfolio from a parent transaction portfolio (which may itself be derived).
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope in which to create the derived transaction portfolio.</param>
        /// <param name="createDerivedTransactionPortfolioRequest">The definition of the derived transaction portfolio. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (Portfolio)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<Portfolio>> CreateDerivedPortfolioWithHttpInfoAsync(string scope, CreateDerivedTransactionPortfolioRequest? createDerivedTransactionPortfolioRequest = default(CreateDerivedTransactionPortfolioRequest?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling DerivedTransactionPortfoliosApi->CreateDerivedPortfolio");
            }


            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.Data = createDerivedTransactionPortfolioRequest;

            localVarRequestOptions.Operation = "DerivedTransactionPortfoliosApi.CreateDerivedPortfolio";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<Portfolio, AbstractOpenAPISchema>("/api/api/derivedtransactionportfolios/{scope}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDerivedPortfolio", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details Delete all the portfolio details for a derived transaction portfolio.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        public DeletedEntityResponse DeleteDerivedPortfolioDetails(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = DeleteDerivedPortfolioDetailsWithHttpInfo(scope, code, effectiveAt, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details Delete all the portfolio details for a derived transaction portfolio.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        public Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteDerivedPortfolioDetailsWithHttpInfo(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling DerivedTransactionPortfoliosApi->DeleteDerivedPortfolioDetails");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling DerivedTransactionPortfoliosApi->DeleteDerivedPortfolioDetails");
            }

            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (effectiveAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Finbourne.Sdk.Client.ClientUtils.ParameterToMultiMap("", "effectiveAt", effectiveAt));
            }

            localVarRequestOptions.Operation = "DerivedTransactionPortfoliosApi.DeleteDerivedPortfolioDetails";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeletedEntityResponse, AbstractOpenAPISchema>("/api/api/derivedtransactionportfolios/{scope}/{code}/details", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDerivedPortfolioDetails", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details Delete all the portfolio details for a derived transaction portfolio.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        public async System.Threading.Tasks.Task<DeletedEntityResponse> DeleteDerivedPortfolioDetailsAsync(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = await DeleteDerivedPortfolioDetailsWithHttpInfoAsync(scope, code, effectiveAt, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EARLY ACCESS] DeleteDerivedPortfolioDetails: Delete derived portfolio details Delete all the portfolio details for a derived transaction portfolio.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the derived transaction portfolio.</param>
        /// <param name="code">The code of the derived transaction portfolio. Together with the scope this uniquely identifies              the derived transaction portfolio.</param>
        /// <param name="effectiveAt">The effective date of the change. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteDerivedPortfolioDetailsWithHttpInfoAsync(string scope, string code, DateTimeOrCutLabel? effectiveAt = default(DateTimeOrCutLabel?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling DerivedTransactionPortfoliosApi->DeleteDerivedPortfolioDetails");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling DerivedTransactionPortfoliosApi->DeleteDerivedPortfolioDetails");
            }


            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (effectiveAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Finbourne.Sdk.Client.ClientUtils.ParameterToMultiMap("", "effectiveAt", effectiveAt));
            }

            localVarRequestOptions.Operation = "DerivedTransactionPortfoliosApi.DeleteDerivedPortfolioDetails";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeletedEntityResponse, AbstractOpenAPISchema>("/api/api/derivedtransactionportfolios/{scope}/{code}/details", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteDerivedPortfolioDetails", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}