/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using Object = System.Object;
using InvalidOperationException = System.InvalidOperationException;
using Exception = System.Exception;
using ArgumentNullException = System.ArgumentNullException;
using SystemEventHandler = System.EventHandler;
using Guid = System.Guid;
using DateTimeOffset = System.DateTimeOffset;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using IApiAccessor = Finbourne.Sdk.Client.IApiAccessor;
using Finbourne.Sdk.Extensions;
using Finbourne.Sdk.Client.Auth;
using Finbourne.Sdk.Services.Lusid.Model;

namespace Finbourne.Sdk.Services.Lusid.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRelationDefinitionsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition
        /// </summary>
        /// <remarks>
        /// Define a new relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>RelationDefinition</returns>
        RelationDefinition CreateRelationDefinition(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition
        /// </summary>
        /// <remarks>
        /// Define a new relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of RelationDefinition</returns>
        Finbourne.Sdk.Client.ApiResponse<RelationDefinition> CreateRelationDefinitionWithHttpInfo(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition
        /// </summary>
        /// <remarks>
        /// Delete the definition of the specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        DeletedEntityResponse DeleteRelationDefinition(string scope, string code, int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition
        /// </summary>
        /// <remarks>
        /// Delete the definition of the specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteRelationDefinitionWithHttpInfo(string scope, string code, int operationIndex = 0, ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition
        /// </summary>
        /// <remarks>
        /// Retrieve the definition of a specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>RelationDefinition</returns>
        RelationDefinition GetRelationDefinition(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition
        /// </summary>
        /// <remarks>
        /// Retrieve the definition of a specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of RelationDefinition</returns>
        Finbourne.Sdk.Client.ApiResponse<RelationDefinition> GetRelationDefinitionWithHttpInfo(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, ConfigurationOptions? opts = null);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRelationDefinitionsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition
        /// </summary>
        /// <remarks>
        /// Define a new relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of RelationDefinition</returns>
        System.Threading.Tasks.Task<RelationDefinition> CreateRelationDefinitionAsync(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition
        /// </summary>
        /// <remarks>
        /// Define a new relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (RelationDefinition)</returns>
        System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<RelationDefinition>> CreateRelationDefinitionWithHttpInfoAsync(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition
        /// </summary>
        /// <remarks>
        /// Delete the definition of the specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        System.Threading.Tasks.Task<DeletedEntityResponse> DeleteRelationDefinitionAsync(string scope, string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition
        /// </summary>
        /// <remarks>
        /// Delete the definition of the specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteRelationDefinitionWithHttpInfoAsync(string scope, string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition
        /// </summary>
        /// <remarks>
        /// Retrieve the definition of a specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of RelationDefinition</returns>
        System.Threading.Tasks.Task<RelationDefinition> GetRelationDefinitionAsync(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition
        /// </summary>
        /// <remarks>
        /// Retrieve the definition of a specified relation.
        /// </remarks>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (RelationDefinition)</returns>
        System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<RelationDefinition>> GetRelationDefinitionWithHttpInfoAsync(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRelationDefinitionsApi : IRelationDefinitionsApiSync, IRelationDefinitionsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RelationDefinitionsApi : IRelationDefinitionsApi
    {
        private Finbourne.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="RelationDefinitionsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public RelationDefinitionsApi(Finbourne.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = configuration;
            this.Client = new Finbourne.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Finbourne.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Finbourne.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RelationDefinitionsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public RelationDefinitionsApi(Finbourne.Sdk.Client.ISynchronousClient client, Finbourne.Sdk.Client.IAsynchronousClient asyncClient, Finbourne.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Finbourne.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Finbourne.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Finbourne.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Finbourne.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Finbourne.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition Define a new relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>RelationDefinition</returns>
        public RelationDefinition CreateRelationDefinition(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<RelationDefinition> localVarResponse = CreateRelationDefinitionWithHttpInfo(createRelationDefinitionRequest, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition Define a new relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of RelationDefinition</returns>
        public Finbourne.Sdk.Client.ApiResponse<RelationDefinition> CreateRelationDefinitionWithHttpInfo(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'createRelationDefinitionRequest' is set
            if (createRelationDefinitionRequest == null)
            {
                throw new ArgumentNullException("Missing required parameter 'createRelationDefinitionRequest' when calling RelationDefinitionsApi->CreateRelationDefinition");
            }

            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createRelationDefinitionRequest;

            localVarRequestOptions.Operation = "RelationDefinitionsApi.CreateRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<RelationDefinition, AbstractOpenAPISchema>("/api/api/relationdefinitions", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition Define a new relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of RelationDefinition</returns>
        public async System.Threading.Tasks.Task<RelationDefinition> CreateRelationDefinitionAsync(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<RelationDefinition> localVarResponse = await CreateRelationDefinitionWithHttpInfoAsync(createRelationDefinitionRequest, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] CreateRelationDefinition: Create a relation definition Define a new relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="createRelationDefinitionRequest">The definition of the new relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (RelationDefinition)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<RelationDefinition>> CreateRelationDefinitionWithHttpInfoAsync(CreateRelationDefinitionRequest createRelationDefinitionRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'createRelationDefinitionRequest' is set
            if (createRelationDefinitionRequest == null)
            {
                throw new ArgumentNullException("Missing required parameter 'createRelationDefinitionRequest' when calling RelationDefinitionsApi->CreateRelationDefinition");
            }


            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = createRelationDefinitionRequest;

            localVarRequestOptions.Operation = "RelationDefinitionsApi.CreateRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<RelationDefinition, AbstractOpenAPISchema>("/api/api/relationdefinitions", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition Delete the definition of the specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>DeletedEntityResponse</returns>
        public DeletedEntityResponse DeleteRelationDefinition(string scope, string code, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = DeleteRelationDefinitionWithHttpInfo(scope, code, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition Delete the definition of the specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of DeletedEntityResponse</returns>
        public Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> DeleteRelationDefinitionWithHttpInfo(string scope, string code, int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling RelationDefinitionsApi->DeleteRelationDefinition");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling RelationDefinitionsApi->DeleteRelationDefinition");
            }

            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "RelationDefinitionsApi.DeleteRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<DeletedEntityResponse, AbstractOpenAPISchema>("/api/api/relationdefinitions/{scope}/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition Delete the definition of the specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of DeletedEntityResponse</returns>
        public async System.Threading.Tasks.Task<DeletedEntityResponse> DeleteRelationDefinitionAsync(string scope, string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse> localVarResponse = await DeleteRelationDefinitionWithHttpInfoAsync(scope, code, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] DeleteRelationDefinition: Delete relation definition Delete the definition of the specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the relation to be deleted.</param>
        /// <param name="code">The code of the relation to be deleted. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (DeletedEntityResponse)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<DeletedEntityResponse>> DeleteRelationDefinitionWithHttpInfoAsync(string scope, string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling RelationDefinitionsApi->DeleteRelationDefinition");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling RelationDefinitionsApi->DeleteRelationDefinition");
            }


            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "RelationDefinitionsApi.DeleteRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<DeletedEntityResponse, AbstractOpenAPISchema>("/api/api/relationdefinitions/{scope}/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition Retrieve the definition of a specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>RelationDefinition</returns>
        public RelationDefinition GetRelationDefinition(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<RelationDefinition> localVarResponse = GetRelationDefinitionWithHttpInfo(scope, code, asAt, opts: opts);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition Retrieve the definition of a specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>ApiResponse of RelationDefinition</returns>
        public Finbourne.Sdk.Client.ApiResponse<RelationDefinition> GetRelationDefinitionWithHttpInfo(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling RelationDefinitionsApi->GetRelationDefinition");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling RelationDefinitionsApi->GetRelationDefinition");
            }

            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (asAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Finbourne.Sdk.Client.ClientUtils.ParameterToMultiMap("", "asAt", asAt));
            }

            localVarRequestOptions.Operation = "RelationDefinitionsApi.GetRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<RelationDefinition, AbstractOpenAPISchema>("/api/api/relationdefinitions/{scope}/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition Retrieve the definition of a specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of RelationDefinition</returns>
        public async System.Threading.Tasks.Task<RelationDefinition> GetRelationDefinitionAsync(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            Finbourne.Sdk.Client.ApiResponse<RelationDefinition> localVarResponse = await GetRelationDefinitionWithHttpInfoAsync(scope, code, asAt, operationIndex, cancellationToken, opts).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// [EXPERIMENTAL] GetRelationDefinition: Get relation definition Retrieve the definition of a specified relation.
        /// </summary>
        /// <exception cref="Finbourne.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <exception cref="ArgumentNullException">Thrown when required parameter is null</exception>
        /// <param name="scope">The scope of the specified relation.</param>
        /// <param name="code">The code of the specified relation. Together with the domain and scope this uniquely              identifies the relation.</param>
        /// <param name="asAt">The asAt datetime at which to retrieve the relation definition. Defaults to return              the latest version of the definition if not specified. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <param name="opts">Options for this request.</param>
        /// <returns>Task of ApiResponse (RelationDefinition)</returns>
        public async System.Threading.Tasks.Task<Finbourne.Sdk.Client.ApiResponse<RelationDefinition>> GetRelationDefinitionWithHttpInfoAsync(string scope, string code, DateTimeOffset? asAt = default(DateTimeOffset?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken), ConfigurationOptions? opts = null)
        {
            // verify the required parameter 'scope' is set
            if (scope == null)
            {
                throw new ArgumentNullException("Missing required parameter 'scope' when calling RelationDefinitionsApi->GetRelationDefinition");
            }

            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new ArgumentNullException("Missing required parameter 'code' when calling RelationDefinitionsApi->GetRelationDefinition");
            }


            Finbourne.Sdk.Client.RequestOptions localVarRequestOptions = new Finbourne.Sdk.Client.RequestOptions();

            if (opts is { TimeoutMs: not null })
            {
                localVarRequestOptions.TimeoutMs = opts.TimeoutMs.Value;
            }
            
            if (opts is { RateLimitRetries: not null })
            {
                localVarRequestOptions.RateLimitRetries = opts.RateLimitRetries.Value;
            }

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Finbourne.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Finbourne.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("scope", Finbourne.Sdk.Client.ClientUtils.ParameterToString(scope)); // path parameter
            localVarRequestOptions.PathParameters.Add("code", Finbourne.Sdk.Client.ClientUtils.ParameterToString(code)); // path parameter
            if (asAt != null)
            {
                localVarRequestOptions.QueryParameters.Add(Finbourne.Sdk.Client.ClientUtils.ParameterToMultiMap("", "asAt", asAt));
            }

            localVarRequestOptions.Operation = "RelationDefinitionsApi.GetRelationDefinition";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (oauth2) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<RelationDefinition, AbstractOpenAPISchema>("/api/api/relationdefinitions/{scope}/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetRelationDefinition", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}