/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Lusid.Model
{
    /// <summary>
    /// EquityShiftDefinition
    /// </summary>
    [DataContract(Name = "EquityShiftDefinition")]
    [JsonConverter(typeof(JsonSubtypes), "ScenarioShiftType")]
    public partial class EquityShiftDefinition : ScenarioShiftDefinition, IEquatable<EquityShiftDefinition>, IValidatableObject
    {
        /// <summary>
        /// Available values: Absolute, Relative, Percentage.
        /// </summary>
        /// <value>Available values: Absolute, Relative, Percentage.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ShiftTypeEnum
        {
            /// <summary>
            /// Enum Absolute for value: Absolute
            /// </summary>
            [EnumMember(Value = "Absolute")]
            Absolute = 1,

            /// <summary>
            /// Enum Relative for value: Relative
            /// </summary>
            [EnumMember(Value = "Relative")]
            Relative = 2,

            /// <summary>
            /// Enum Percentage for value: Percentage
            /// </summary>
            [EnumMember(Value = "Percentage")]
            Percentage = 3
        }

        /// <summary>
        /// Available values: Absolute, Relative, Percentage.
        /// </summary>
        /// <value>Available values: Absolute, Relative, Percentage.</value>
        [DataMember(Name = "shiftType", IsRequired = true, EmitDefaultValue = true)]
        public ShiftTypeEnum ShiftType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="EquityShiftDefinition" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EquityShiftDefinition() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EquityShiftDefinition" /> class.
        /// </summary>
        /// <param name="instrument">instrument (required).</param>
        /// <param name="amount">amount (required).</param>
        /// <param name="shiftType">Available values: Absolute, Relative, Percentage. (required).</param>
        /// <param name="scenarioShiftType">Available values: RateCurveShiftDefinition, FxShiftDefinition, EquityShiftDefinition, VolSurfaceShiftDefinition. (required) (default to ScenarioShiftTypeEnum.RateCurveShiftDefinition).</param>
        public EquityShiftDefinition(string instrument = default(string), decimal amount = default(decimal), ShiftTypeEnum shiftType = default(ShiftTypeEnum), ScenarioShiftTypeEnum scenarioShiftType = default(ScenarioShiftTypeEnum)) : base()
        {
            // to ensure "instrument" is required (not null)
            if (instrument == null)
            {
                throw new ArgumentNullException("instrument is a required property for EquityShiftDefinition and cannot be null");
            }
            this.Instrument = instrument;
            
            this.Amount = amount;
            
            // to ensure "shiftType" is a defined enum value
            if (!System.Enum.IsDefined(typeof(ShiftTypeEnum), shiftType))
            {
                throw new ArgumentException("shiftType is a required property for EquityShiftDefinition and must be a defined value");
            }
            
            this.ShiftType = shiftType;
            
            // to ensure "scenarioShiftType" is a defined enum value
            if (!System.Enum.IsDefined(typeof(ScenarioShiftTypeEnum), scenarioShiftType))
            {
                throw new ArgumentException("scenarioShiftType is a required property for EquityShiftDefinition and must be a defined value");
            }
            
            this.ScenarioShiftType = scenarioShiftType;
        }

        /// <summary>
        /// Gets or Sets Instrument
        /// </summary>
        [DataMember(Name = "instrument", IsRequired = true, EmitDefaultValue = true)]
        public string Instrument { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EquityShiftDefinition {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Instrument: ").Append(Instrument).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  ShiftType: ").Append(ShiftType).Append("\n");
            sb.Append("  ScenarioShiftType: ").Append(ScenarioShiftType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EquityShiftDefinition);
        }

        /// <summary>
        /// Returns true if EquityShiftDefinition instances are equal
        /// </summary>
        /// <param name="input">Instance of EquityShiftDefinition to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EquityShiftDefinition input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.Instrument == input.Instrument ||
                    (this.Instrument != null &&
                    this.Instrument.Equals(input.Instrument))
                ) && base.Equals(input) && 
                (
                    this.Amount == input.Amount ||
                    this.Amount.Equals(input.Amount)
                ) && base.Equals(input) && 
                (
                    this.ShiftType == input.ShiftType ||
                    this.ShiftType.Equals(input.ShiftType)
                ) && base.Equals(input) && 
                (
                    this.ScenarioShiftType == input.ScenarioShiftType ||
                    this.ScenarioShiftType.Equals(input.ScenarioShiftType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Instrument != null)
                {
                    hashCode = (hashCode * 59) + this.Instrument.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                hashCode = (hashCode * 59) + this.ShiftType.GetHashCode();
                hashCode = (hashCode * 59) + this.ScenarioShiftType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }
}
