/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Lusid.Model
{
    /// <summary>
    /// Model options for instruments of type flexibleDeposit and flexibleLoan when used on a standalone basis.
    /// </summary>
    [DataContract(Name = "FlexibleLoanPricerOptions")]
    [JsonConverter(typeof(JsonSubtypes), "ModelOptionsType")]
    public partial class FlexibleLoanPricerOptions : ModelOptions, IEquatable<FlexibleLoanPricerOptions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlexibleLoanPricerOptions" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FlexibleLoanPricerOptions() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FlexibleLoanPricerOptions" /> class.
        /// </summary>
        /// <param name="setCleanPVToZero">If set to true the CleanPV will be set to zero in valuations and PV will effectively just be the Accrual. (required).</param>
        /// <param name="modelOptionsType">Available values: Invalid, OpaqueModelOptions, EmptyModelOptions, IndexModelOptions, FxForwardModelOptions, FundingLegModelOptions, EquityModelOptions, CdsModelOptions, FlexibleLoanPricerOptions. (required) (default to ModelOptionsTypeEnum.Invalid).</param>
        public FlexibleLoanPricerOptions(bool setCleanPVToZero = default(bool), ModelOptionsTypeEnum modelOptionsType = default(ModelOptionsTypeEnum)) : base()
        {
            
            this.SetCleanPVToZero = setCleanPVToZero;
            
            // to ensure "modelOptionsType" is a defined enum value
            if (!System.Enum.IsDefined(typeof(ModelOptionsTypeEnum), modelOptionsType))
            {
                throw new ArgumentException("modelOptionsType is a required property for FlexibleLoanPricerOptions and must be a defined value");
            }
            
            this.ModelOptionsType = modelOptionsType;
        }

        /// <summary>
        /// If set to true the CleanPV will be set to zero in valuations and PV will effectively just be the Accrual.
        /// </summary>
        /// <value>If set to true the CleanPV will be set to zero in valuations and PV will effectively just be the Accrual.</value>
        [DataMember(Name = "setCleanPVToZero", IsRequired = true, EmitDefaultValue = true)]
        public bool SetCleanPVToZero { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FlexibleLoanPricerOptions {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  SetCleanPVToZero: ").Append(SetCleanPVToZero).Append("\n");
            sb.Append("  ModelOptionsType: ").Append(ModelOptionsType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FlexibleLoanPricerOptions);
        }

        /// <summary>
        /// Returns true if FlexibleLoanPricerOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of FlexibleLoanPricerOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FlexibleLoanPricerOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.SetCleanPVToZero == input.SetCleanPVToZero ||
                    this.SetCleanPVToZero.Equals(input.SetCleanPVToZero)
                ) && base.Equals(input) && 
                (
                    this.ModelOptionsType == input.ModelOptionsType ||
                    this.ModelOptionsType.Equals(input.ModelOptionsType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                hashCode = (hashCode * 59) + this.SetCleanPVToZero.GetHashCode();
                hashCode = (hashCode * 59) + this.ModelOptionsType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            yield break;
        }
    }
}
