/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Lusid.Model
{
    /// <summary>
    /// Defines FxShiftMode
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum FxShiftMode
    {
        /// <summary>
        /// Enum Absolute for value: absolute
        /// </summary>
        [EnumMember(Value = "absolute")]
        Absolute = 1,

        /// <summary>
        /// Enum Relative for value: relative
        /// </summary>
        [EnumMember(Value = "relative")]
        Relative = 2,

        /// <summary>
        /// Enum Percentage for value: percentage
        /// </summary>
        [EnumMember(Value = "percentage")]
        Percentage = 3
    }

}
