/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Lusid.Model
{
    /// <summary>
    /// InstrumentActivityAdjustment
    /// </summary>
    [DataContract(Name = "InstrumentActivityAdjustment")]
    [JsonConverter(typeof(JsonSubtypes), "NavActivityAdjustmentType")]
    public partial class InstrumentActivityAdjustment : NavActivityAdjustmentResponse, IEquatable<InstrumentActivityAdjustment>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentActivityAdjustment" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InstrumentActivityAdjustment() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InstrumentActivityAdjustment" /> class.
        /// </summary>
        /// <param name="navActivityAdjustmentSource">The post closed activity source of the given entity, for example Manual. Available values: Undefined, Manual, Auto. (required).</param>
        /// <param name="asAt">The asAt time for which the adjustment is being applied. (required).</param>
        /// <param name="scope">The Scope of the given entity (required).</param>
        /// <param name="lusidInstrumentId">The LusidInstrumentId of the given entity (required).</param>
        /// <param name="navActivityAdjustmentType">The type of the entity being applied, for example a PortfolioTransaction. Available values: PortfolioTransactionAdjustment, PortfolioSettlementInstructionAdjustment, InstrumentActivityAdjustment, QuoteActivityAdjustment, ComplexMarketDataActivityAdjustment. (required) (default to NavActivityAdjustmentTypeEnum.PortfolioTransactionAdjustment).</param>
        public InstrumentActivityAdjustment(string navActivityAdjustmentSource = default(string), DateTimeOffset asAt = default(DateTimeOffset), string scope = default(string), string lusidInstrumentId = default(string), NavActivityAdjustmentTypeEnum navActivityAdjustmentType = default(NavActivityAdjustmentTypeEnum)) : base()
        {
            // to ensure "navActivityAdjustmentSource" is required (not null)
            if (navActivityAdjustmentSource == null)
            {
                throw new ArgumentNullException("navActivityAdjustmentSource is a required property for InstrumentActivityAdjustment and cannot be null");
            }
            this.NavActivityAdjustmentSource = navActivityAdjustmentSource;
            
            this.AsAt = asAt;
            // to ensure "scope" is required (not null)
            if (scope == null)
            {
                throw new ArgumentNullException("scope is a required property for InstrumentActivityAdjustment and cannot be null");
            }
            this.Scope = scope;
            // to ensure "lusidInstrumentId" is required (not null)
            if (lusidInstrumentId == null)
            {
                throw new ArgumentNullException("lusidInstrumentId is a required property for InstrumentActivityAdjustment and cannot be null");
            }
            this.LusidInstrumentId = lusidInstrumentId;
            
            // to ensure "navActivityAdjustmentType" is a defined enum value
            if (!System.Enum.IsDefined(typeof(NavActivityAdjustmentTypeEnum), navActivityAdjustmentType))
            {
                throw new ArgumentException("navActivityAdjustmentType is a required property for InstrumentActivityAdjustment and must be a defined value");
            }
            
            this.NavActivityAdjustmentType = navActivityAdjustmentType;
        }

        /// <summary>
        /// The post closed activity source of the given entity, for example Manual. Available values: Undefined, Manual, Auto.
        /// </summary>
        /// <value>The post closed activity source of the given entity, for example Manual. Available values: Undefined, Manual, Auto.</value>
        [DataMember(Name = "navActivityAdjustmentSource", IsRequired = true, EmitDefaultValue = true)]
        public string NavActivityAdjustmentSource { get; set; }

        /// <summary>
        /// The asAt time for which the adjustment is being applied.
        /// </summary>
        /// <value>The asAt time for which the adjustment is being applied.</value>
        [DataMember(Name = "asAt", IsRequired = true, EmitDefaultValue = true)]
        public DateTimeOffset AsAt { get; set; }

        /// <summary>
        /// The Scope of the given entity
        /// </summary>
        /// <value>The Scope of the given entity</value>
        [DataMember(Name = "scope", IsRequired = true, EmitDefaultValue = true)]
        public string Scope { get; set; }

        /// <summary>
        /// The LusidInstrumentId of the given entity
        /// </summary>
        /// <value>The LusidInstrumentId of the given entity</value>
        [DataMember(Name = "lusidInstrumentId", IsRequired = true, EmitDefaultValue = true)]
        public string LusidInstrumentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InstrumentActivityAdjustment {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  NavActivityAdjustmentSource: ").Append(NavActivityAdjustmentSource).Append("\n");
            sb.Append("  AsAt: ").Append(AsAt).Append("\n");
            sb.Append("  Scope: ").Append(Scope).Append("\n");
            sb.Append("  LusidInstrumentId: ").Append(LusidInstrumentId).Append("\n");
            sb.Append("  NavActivityAdjustmentType: ").Append(NavActivityAdjustmentType).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InstrumentActivityAdjustment);
        }

        /// <summary>
        /// Returns true if InstrumentActivityAdjustment instances are equal
        /// </summary>
        /// <param name="input">Instance of InstrumentActivityAdjustment to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InstrumentActivityAdjustment input)
        {
            if (input == null)
            {
                return false;
            }
            return base.Equals(input) && 
                (
                    this.NavActivityAdjustmentSource == input.NavActivityAdjustmentSource ||
                    (this.NavActivityAdjustmentSource != null &&
                    this.NavActivityAdjustmentSource.Equals(input.NavActivityAdjustmentSource))
                ) && base.Equals(input) && 
                (
                    this.AsAt == input.AsAt ||
                    (this.AsAt != null &&
                    this.AsAt.Equals(input.AsAt))
                ) && base.Equals(input) && 
                (
                    this.Scope == input.Scope ||
                    (this.Scope != null &&
                    this.Scope.Equals(input.Scope))
                ) && base.Equals(input) && 
                (
                    this.LusidInstrumentId == input.LusidInstrumentId ||
                    (this.LusidInstrumentId != null &&
                    this.LusidInstrumentId.Equals(input.LusidInstrumentId))
                ) && base.Equals(input) && 
                (
                    this.NavActivityAdjustmentType == input.NavActivityAdjustmentType ||
                    this.NavActivityAdjustmentType.Equals(input.NavActivityAdjustmentType)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.NavActivityAdjustmentSource != null)
                {
                    hashCode = (hashCode * 59) + this.NavActivityAdjustmentSource.GetHashCode();
                }
                if (this.AsAt != null)
                {
                    hashCode = (hashCode * 59) + this.AsAt.GetHashCode();
                }
                if (this.Scope != null)
                {
                    hashCode = (hashCode * 59) + this.Scope.GetHashCode();
                }
                if (this.LusidInstrumentId != null)
                {
                    hashCode = (hashCode * 59) + this.LusidInstrumentId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NavActivityAdjustmentType.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            foreach (var x in base.BaseValidate(validationContext))
            {
                yield return x;
            }
            // Scope (string) pattern
            Regex regexScope = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (this.Scope != null && false == regexScope.Match(this.Scope).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Scope, must match a pattern of " + regexScope, new [] { "Scope" });
            }

            // LusidInstrumentId (string) pattern
            Regex regexLusidInstrumentId = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (this.LusidInstrumentId != null && false == regexLusidInstrumentId.Match(this.LusidInstrumentId).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for LusidInstrumentId, must match a pattern of " + regexLusidInstrumentId, new [] { "LusidInstrumentId" });
            }

            yield break;
        }
    }
}
