/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Lusid.Model
{
    /// <summary>
    /// A definition for the period you wish to re open
    /// </summary>
    [DataContract(Name = "ReOpenPeriodDiaryEntryRequest")]
    public partial class ReOpenPeriodDiaryEntryRequest : IEquatable<ReOpenPeriodDiaryEntryRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReOpenPeriodDiaryEntryRequest" /> class.
        /// </summary>
        /// <param name="diaryEntryCode">Unique code assigned to a period. When left blank last period will be used..</param>
        public ReOpenPeriodDiaryEntryRequest(string diaryEntryCode = default(string))
        {
            this.DiaryEntryCode = diaryEntryCode;
        }

        /// <summary>
        /// Unique code assigned to a period. When left blank last period will be used.
        /// </summary>
        /// <value>Unique code assigned to a period. When left blank last period will be used.</value>
        [DataMember(Name = "diaryEntryCode", EmitDefaultValue = true)]
        public string DiaryEntryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReOpenPeriodDiaryEntryRequest {\n");
            sb.Append("  DiaryEntryCode: ").Append(DiaryEntryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReOpenPeriodDiaryEntryRequest);
        }

        /// <summary>
        /// Returns true if ReOpenPeriodDiaryEntryRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReOpenPeriodDiaryEntryRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReOpenPeriodDiaryEntryRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DiaryEntryCode == input.DiaryEntryCode ||
                    (this.DiaryEntryCode != null &&
                    this.DiaryEntryCode.Equals(input.DiaryEntryCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DiaryEntryCode != null)
                {
                    hashCode = (hashCode * 59) + this.DiaryEntryCode.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // DiaryEntryCode (string) pattern
            Regex regexDiaryEntryCode = new Regex(@"^[a-zA-Z0-9\-_]+$", RegexOptions.CultureInvariant);
            if (false == regexDiaryEntryCode.Match(this.DiaryEntryCode).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for DiaryEntryCode, must match a pattern of " + regexDiaryEntryCode, new [] { "DiaryEntryCode" });
            }

            yield break;
        }
    }
}
