/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Drive.Model
{
    /// <summary>
    /// DTO representing the update of the name or path of a file
    /// </summary>
    [DataContract(Name = "UpdateFile")]
    public partial class UpdateFile : IEquatable<UpdateFile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFile" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateFile() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateFile" /> class.
        /// </summary>
        /// <param name="path">Path of the updated file (required).</param>
        /// <param name="name">Name of the updated file (required).</param>
        public UpdateFile(string path = default(string), string name = default(string))
        {
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for UpdateFile and cannot be null");
            }
            this.Path = path;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for UpdateFile and cannot be null");
            }
            this.Name = name;
        }

        /// <summary>
        /// Path of the updated file
        /// </summary>
        /// <value>Path of the updated file</value>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// Name of the updated file
        /// </summary>
        /// <value>Name of the updated file</value>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateFile {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UpdateFile);
        }

        /// <summary>
        /// Returns true if UpdateFile instances are equal
        /// </summary>
        /// <param name="input">Instance of UpdateFile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UpdateFile input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Path == input.Path ||
                    (this.Path != null &&
                    this.Path.Equals(input.Path))
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Path != null)
                {
                    hashCode = (hashCode * 59) + this.Path.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Path (string) pattern
            Regex regexPath = new Regex(@"^[\/a-zA-Z0-9 \-_]+$", RegexOptions.CultureInvariant);
            if (false == regexPath.Match(this.Path).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Path, must match a pattern of " + regexPath, new [] { "Path" });
            }

            // Name (string) pattern
            Regex regexName = new Regex(@"^[A-Za-z0-9_\-\.]+[A-Za-z0-9_\-\. ]*$", RegexOptions.CultureInvariant);
            if (false == regexName.Match(this.Name).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, must match a pattern of " + regexName, new [] { "Name" });
            }

            yield break;
        }
    }
}
