/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Sockets;
using System.Reflection;
using Finbourne.Sdk.Client;

namespace Finbourne.Sdk.Extensions
{
    /// <summary>
    /// Factory to provide instances of the autogenerated Api
    /// </summary>
    public interface IApiFactory
    {
        /// <summary>
        /// Return the specific autogenerated Api
        /// </summary>
        TApi Api<TApi>() where TApi : class, IApiAccessor;
    }

    /// <inheritdoc />
    public class ApiFactory : IApiFactory
    {
        private static readonly IEnumerable<Type> ApiTypes = Assembly.GetAssembly(typeof(ApiClient))
            .GetTypes()
            .Where(t => typeof(IApiAccessor).IsAssignableFrom(t) && t.IsClass);

        private readonly IReadOnlyDictionary<Type, IApiAccessor> _apis;

        /// <summary>
        /// Create a new factory using the specified configuration
        /// </summary>
        /// <param name="apiConfiguration">Configuration for the ClientCredentialsFlowTokenProvider, usually sourced from a "secrets.json" file</param>
        /// <param name="defaultConfiguration">Default configuration values to use when not specified in <paramref name="apiConfiguration"/>. When null, falls back to <see cref="GlobalConfiguration.Instance"/>.</param>
        /// <param name="retryConfiguration">Custom retry policies applied to every request made through this factory. When null, falls back to <paramref name="defaultConfiguration"/>'s RetryConfiguration, else the SDK default retry policy.</param>
        public ApiFactory(ApiConfiguration apiConfiguration, IReadableConfiguration? defaultConfiguration = null, RetryConfiguration? retryConfiguration = null)
        {
            if (apiConfiguration == null) throw new ArgumentNullException(nameof(apiConfiguration));

            var effectiveDefaults = defaultConfiguration ?? GlobalConfiguration.Instance;

            // Validate Uris
            // note: could employ a factory pattern here to create ITokenProvider in case more branching is required in the future:
            ITokenProvider tokenProvider;
            if (!string.IsNullOrWhiteSpace(apiConfiguration.PersonalAccessToken)) // the personal access token takes precedence over other methods of authentication
            {
                tokenProvider = new PersonalAccessTokenProvider(apiConfiguration.PersonalAccessToken);
            }
            else {
                if (!Uri.TryCreate(apiConfiguration.TokenUrl, UriKind.Absolute, out var _))
                {
                    throw new UriFormatException($"Invalid Token Uri: {apiConfiguration.TokenUrl}");
                }
                tokenProvider = new ClientCredentialsFlowTokenProvider(apiConfiguration);
            }

            if (!Uri.TryCreate(apiConfiguration.BaseUrl, UriKind.Absolute, out var _))
            {
                if (string.IsNullOrWhiteSpace(apiConfiguration.BaseUrl))
                    throw new ArgumentNullException(
                        nameof(apiConfiguration.BaseUrl),
                        $"BaseUrl Uri missing. Please specify either FBN_BASE_URL environment variable or baseUrl in secrets.json.");

                throw new UriFormatException($"Invalid Uri: {apiConfiguration.BaseUrl}");
            }

            // Create configuration
            var configuration = new TokenProviderConfiguration(tokenProvider)
            {
                BasePath = apiConfiguration.BaseUrl
            };

            // if the timeout config has been specified, use this, else use the value from the effective defaults
            configuration.TimeoutMs = apiConfiguration.TimeoutMs ?? effectiveDefaults.TimeoutMs;

            // if the rate limit retry config has been specified, use this, else use the value from the effective defaults
            configuration.RateLimitRetries = apiConfiguration.RateLimitRetries ?? effectiveDefaults.RateLimitRetries;

            configuration.NumberOfRetries = apiConfiguration.NumberOfRetries;
            configuration.RetryBackoffMs = apiConfiguration.RetryBackoffMs;

            // if not set here, MergeWithConfiguration below falls through to the effective defaults' RetryConfiguration
            configuration.RetryConfiguration = retryConfiguration;

            if(!String.IsNullOrWhiteSpace(apiConfiguration.ApplicationName))
            {
                configuration.DefaultHeaders.Add("X-LUSID-Application", apiConfiguration.ApplicationName);
            }
            if (apiConfiguration.AdditionalHeaders != null)
            {
                foreach (var header in apiConfiguration.AdditionalHeaders)
                {
                    configuration.DefaultHeaders[header.Key] = header.Value;
                }
            }
            configuration.MergeWithConfiguration(effectiveDefaults);

            _apis = Init(configuration);
        }

        /// <summary>
        /// Create a new factory using the specified configuration
        /// </summary>
        /// <param name="configuration">A set of configuration settings</param>
        /// <param name="additionalHeaders">Additional headers to include on every request</param>
        /// <param name="defaultConfiguration">Default configuration values to merge. When null, falls back to <see cref="GlobalConfiguration.Instance"/>.</param>
        /// <param name="retryConfiguration">Custom retry policies applied to every request made through this factory. A RetryConfiguration already set on <paramref name="configuration"/> takes precedence.</param>
        public ApiFactory(Client.Configuration configuration, IDictionary<string, string>? additionalHeaders = null, IReadableConfiguration? defaultConfiguration = null, RetryConfiguration? retryConfiguration = null)
        {
            if (configuration == null) throw new ArgumentNullException(nameof(configuration));
            if (additionalHeaders != null)
            {
                foreach (var header in additionalHeaders)
                {
                    configuration.DefaultHeaders[header.Key] = header.Value;
                }
            }
            configuration.RetryConfiguration = configuration.RetryConfiguration ?? retryConfiguration;
            configuration.MergeWithConfiguration(defaultConfiguration ?? GlobalConfiguration.Instance);

            _apis = Init(configuration);
        }

        /// <inheritdoc />
        public TApi Api<TApi>() where TApi : class, IApiAccessor
        {
            _apis.TryGetValue(typeof(TApi), out var api);

            if (api == null)
            {
                throw new InvalidOperationException($"Unable to find api: {typeof(TApi)}");
            }

            return api as TApi;
        }

        private static Dictionary<Type, IApiAccessor> Init(Client.Configuration configuration)
        {
            var dict = new Dictionary<Type, IApiAccessor>();
            foreach (Type api in ApiTypes)
            {
                if (!(Activator.CreateInstance(api, configuration) is IApiAccessor impl))
                {
                    throw new Exception($"Unable to create type {api}");
                }

                // Replace the default implementation of the ExceptionFactory with a custom one defined by FINBOURNE
                impl.ExceptionFactory = ExceptionHandler.CustomExceptionFactory;
                var @interface = api.GetInterfaces()
                    .First(i => typeof(IApiAccessor).IsAssignableFrom(i));

                dict[api] = impl;
                dict[@interface] = impl;
            }

            return dict;
        }
    }
}