/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;

namespace Finbourne.Sdk.Extensions
{
    /// <summary>
    /// An exception thrown when config parameters are either missing or invalid
    /// </summary>
    public class ConfigurationException : Exception
    {
        /// <inheritdoc />
        public ConfigurationException(string message) : base(message)
        {
        }
    }
}