/*
 * Merged OpenAPI Specification
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Finbourne.Sdk.Client.OpenAPIDateConverter;

namespace Finbourne.Sdk.Services.Access.Model
{
    /// <summary>
    /// Request body used to add Policies to a Role
    /// </summary>
    [DataContract(Name = "AddPolicyToRoleRequest")]
    public partial class AddPolicyToRoleRequest : IEquatable<AddPolicyToRoleRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddPolicyToRoleRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddPolicyToRoleRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddPolicyToRoleRequest" /> class.
        /// </summary>
        /// <param name="policies">Identifiers of policies to add to a role (required).</param>
        public AddPolicyToRoleRequest(List<PolicyId> policies = default(List<PolicyId>))
        {
            // to ensure "policies" is required (not null)
            if (policies == null)
            {
                throw new ArgumentNullException("policies is a required property for AddPolicyToRoleRequest and cannot be null");
            }
            this.Policies = policies;
        }

        /// <summary>
        /// Identifiers of policies to add to a role
        /// </summary>
        /// <value>Identifiers of policies to add to a role</value>
        [DataMember(Name = "policies", IsRequired = true, EmitDefaultValue = true)]
        public List<PolicyId> Policies { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddPolicyToRoleRequest {\n");
            sb.Append("  Policies: ").Append(Policies).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AddPolicyToRoleRequest);
        }

        /// <summary>
        /// Returns true if AddPolicyToRoleRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AddPolicyToRoleRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AddPolicyToRoleRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Policies == input.Policies ||
                    this.Policies != null &&
                    input.Policies != null &&
                    this.Policies.SequenceEqual(input.Policies)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Policies != null)
                {
                    hashCode = (hashCode * 59) + this.Policies.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
